sudo: required
services:
  - docker

script:
  - docker build -t guilhermegpg/pasqualini-client ./client
  - docker build -t guilhermegpg/pasqualini-api ./api
  - docker build -t guilhermegpg/pasqualini-nginx ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push guilhermegpg/pasqualini-client
  - docker push guilhermegpg/pasqualini-api
  - docker push guilhermegpg/pasqualini-nginx

deploy:
  provider: elasticbeanstalk
  region: sa-east-1
  app: pasqualini
  env: Pasqualini-env
  bucket_name: elasticbeanstalk-sa-east-1-352251318230
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
